git:
  depth: false
language: java
addons:
  sonarcloud:
    organization: "v-smeets-github"
script:
  - '
    case "$TRAVIS_BRANCH" in
      (master) branchTarget="";;
      (develop) branchTarget="master";;
      (*) branchTarget="develop";;
    esac;
    mvn
      --define sonar.branch.target="$branchTarget"
      clean
      install
      sonar:sonar
    | grep --invert-match ''^Hibernate:''
    | fgrep --invert-match ''o.s.t.c.transaction.TransactionContext''
    '
