git:
  depth: false
language: java
addons:
  sonarcloud:
    organization: "v-smeets-github"
script:
  - '
    setState=$(set +o);
    set -o errexit -o pipefail -o xtrace;
    branchName="$TRAVIS_BRANCH";
    case "$branchName" in
      (master) branchTarget="";;
      (develop) branchTarget="master";;
      (*) branchTarget="develop";;
    esac;
    mvn
      --define sonar.branch.name="$branchName"
      --define sonar.branch.target="$branchTarget"
      clean
      install
      sonar:sonar
    | fgrep --invert-match ''o.s.t.c.transaction.TransactionContext'';
    set +vx; eval "$setState";
    '
