git:
  depth: false
language: java
addons:
  sonarcloud:
    organization: "v-smeets-github"
script:
  - |
    mvn clean install sonar:sonar \
    | grep --invert-match '^Hibernate:' \
    | fgrep --invert-match 'o.s.t.c.transaction.TransactionContext'
