/**
 * Copyright (C) 2019 Vincent Smeets
 * <p>
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or any later version.
 * <p>
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * <p>
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 */
package nl.vsmeets.amr.libs.junit.impl;

import java.time.ZoneOffset;

import nl.vsmeets.amr.libs.junit.RandomLocalDateTimeGenerator;

/**
 * Constant values used by the {@link RandomLocalDateTimeGenerator}.
 *
 * @author vincent
 */
public final class LocalDateTimeGeneratorConstants {

  /**
   * The minimum number of seconds that can be generated by the
   * {@link RandomLocalDateTimeGenerator}. This still leaves room for a valid
   * {@link ZoneOffset}.<br>
   * This is the same value as given by the function
   * <code>LocalDateTime.MIN.toEpochSecond(ZoneOffset.MIN)</code>
   */
  public static final long MIN_SECONDS = -31_557_014_135_532_000L;

  /**
   * The maximum number of seconds that can be generated by the
   * {@link RandomLocalDateTimeGenerator}. This still leaves room for a valid
   * {@link ZoneOffset}.<br>
   * This is the same value as given by the function
   * <code>LocalDateTime.MAX.toEpochSecond(ZoneOffset.MAX)</code>
   */
  public static final long MAX_SECONDS = 31_556_889_832_715_999L;

  /**
   * No instance can be created.
   */
  private LocalDateTimeGeneratorConstants() {
  }

}
